### ISSUE TITLE
Demo 2 Feedback (24.11.21)

### ISSUE THREAD

**Issue by wolf1128** [Team17se2/KIRUNA_EXPLORER_se2_2024_Team_17#3]
Dear Team 17 members,

Based on the Demo 2 presentation, we have couple of suggestions for you as the following.
- According to KX7, one or more resources can be uploaded which is not implemented yet.
- Input field for searching is a bit small for long document titles.
- There no way to modify the georeference in the form after selecting them. So, the user forces to come back to the main page.

Everything else is OK. You did a great job! 
We wish you all the best in the rest of the project.

Regards,
Team 03 members.

**Comment by pex9** [comment]
Dear Wolf1128,

I am pleased to inform you that we have successfully addressed all the issues you described.

Best regards,
Team 17 members.
